applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  artifactory.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  artifactory.postgresql.postgresqlPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False  # Default is False
        base64: True           # Default is True
  artifactory.artifactory.masterKey:
    title: 'Artifactory requires a unique master key'
    description: 'You can generate one with the command: openssl rand -hex 32'
    default: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
    type: string
  artifactoryImage:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog-jcr:$ARTIFACTORY_VERSION
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: artifactory-jcr.artifactory.artifactory.image.repository
            after: artifactory-jcr.artifactory.artifactory.image.version
  artifactory.artifactory.persistence.size:
    title: Disk allocation to Artifactory nodes
    type: string
    default: "200Gi"
  artifactory.artifactory.primary.resources.requests.cpu:
    title: CPU units for primary node
    type: string
    default: "100m"
  artifactory.artifactory.primary.resources.requests.memory:
    title: Memory for primary node
    type: string
    default: "512M"
  artifactory.artifactory.primary.resources.limits.cpu:
    title: CPU units for primary node (limit)
    type: string
    default: "4"
  artifactory.artifactory.primary.resources.limits.memory:
    title: Memory for primary node (limit)
    type: string
    default: "8G"
  artifactory.artifactory.node.resources.requests.cpu:
    title: CPU units per node
    type: string
    default: "100m"
  artifactory.artifactory.node.resources.requests.memory:
    title: Memory per node
    type: string
    default: "512M"
  artifactory.artifactory.node.resources.limits.cpu:
    title: CPU units per node (limit)
    type: string
    default: "4"
  artifactory.artifactory.node.resources.limits.memory:
    title: Memory per node (limit)
    type: string
    default: "8G"
  artifactory.artifactory.javaOpts.other:
    title: The following Java options are passed to the java process running Artifactory.
    type: string
    default: "-server -Xms1g -Xmx6g -Xss256k -XX:+UseG1GC"
  artifactoryNginxImage:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog-jcr/nginx:$ARTIFACTORY_VERSION
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: artifactory-jcr.artifactory.nginx.image.repository
            after: artifactory-jcr.artifactory.nginx.image.version
  artifactory.nginx.service.type:
    title: 'Nginx Service Type'
    description: 'Nginx Service Type. LoadBalancer/NodePort/ClusterIP'
    default: 'LoadBalancer'
    type: string
  artifactory.nginx.service.loadBalancerIP:
    title: 'Provide static ip address'
    description: 'Provide static ip address for LoadBalancer. Optional for GKE.'
    type: string
  artifactory.nginx.tlsSecretName:
    title: 'Nginx SSL Secret name'
    description: 'The SSL secret that will be used by the Nginx pod'
    type: string
required:
- name
- namespace
- artifactory.serviceAccount.name
- artifactory.postgresql.postgresqlPassword
- artifactory.artifactory.masterKey
- artifactoryImage
- artifactory.artifactory.persistence.size
- artifactory.artifactory.primary.resources.requests.cpu
- artifactory.artifactory.primary.resources.requests.memory
- artifactory.artifactory.primary.resources.limits.cpu
- artifactory.artifactory.primary.resources.limits.memory
- artifactory.artifactory.node.resources.requests.cpu
- artifactory.artifactory.node.resources.requests.memory
- artifactory.artifactory.node.resources.limits.cpu
- artifactory.artifactory.node.resources.limits.memory
- artifactory.artifactory.javaOpts.other
- artifactoryNginxImage
- artifactory.nginx.service.type
