applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  artifactory-ha.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  #postgresImage:
  #  type: string
  #  default: gcr.io/jfrog-gc-mp/jfrog-artifactory/postgres:9.6
  #  x-google-marketplace:
  #    type: IMAGE
  #    image:
  #      generatedProperties:
  #        splitByColon:
  #          before: artifactory-ha.postgresql.image
  #          after: artifactory-ha.postgresql.imageTag
  artifactory-ha.postgresql.postgresPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False  # Default is False
        base64: True           # Default is True
  artifactory-ha.artifactory.masterKey:
    title: 'Artifactory requires a unique master key'
    description: 'You can generate one with the command: openssl rand -hex 32'
    default: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
    type: string
  artifactoryImage:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog-artifactory:6.15.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: artifactory-ha.artifactory.image.repository
            after: artifactory-ha.artifactory.image.version
  artifactory-ha.artifactory.persistence.size:
    title: Disk allocation to Artifactory nodes
    type: string
    default: "200Gi"
  artifactory-ha.artifactory.primary.resources.requests.cpu:
    title: CPU units for primary node
    type: string
    default: "100m"
  artifactory-ha.artifactory.primary.resources.requests.memory:
    title: Memory for primary node
    type: string
    default: "512M"
  artifactory-ha.artifactory.primary.resources.limits.cpu:
    title: CPU units for primary node (limit)
    type: string
    default: "4"
  artifactory-ha.artifactory.primary.resources.limits.memory:
    title: Memory for primary node (limit)
    type: string
    default: "8G"
  artifactory-ha.artifactory.node.replicaCount:
    type: integer
    title: 'Artifactory Member Node count'
    description: 'Artifactory Member Node count (1 Primary + 2 Member = 3 Node Cluster)'
    default: 2
    minimum: 1
    maximum: 10
  artifactory-ha.artifactory.node.resources.requests.cpu:
    title: CPU units per node
    type: string
    default: "100m"
  artifactory-ha.artifactory.node.resources.requests.memory:
    title: Memory per node
    type: string
    default: "512M"
  artifactory-ha.artifactory.node.resources.limits.cpu:
    title: CPU units per node (limit)
    type: string
    default: "4"
  artifactory-ha.artifactory.node.resources.limits.memory:
    title: Memory per node (limit)
    type: string
    default: "8G"
  artifactory-ha.artifactory.javaOpts.other:
    title: The following Java options are passed to the java process running Artifactory.
    type: string
    default: "-server -Xms1g -Xmx6g -Xss256k -XX:+UseG1GC"
  artifactoryNginxImage:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog-artifactory/nginx-artifactory-pro:6.15.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: artifactory-ha.nginx.image.repository
            after: artifactory-ha.nginx.image.version
  artifactory-ha.nginx.service.type:
    title: 'Nginx Service Type'
    description: 'Nginx Service Type. LoadBalancer/NodePort/ClusterIP'
    default: 'LoadBalancer'
    type: string
  artifactory-ha.nginx.service.loadBalancerIP:
    title: 'Provide static ip address'
    description: 'Provide static ip address for LoadBalancer. Optional for GKE.'
    type: string
  artifactory-ha.nginx.tlsSecretName:
    title: 'Nginx SSL Secret name'
    description: 'The SSL secret that will be used by the Nginx pod'
    type: string
required:
- name
- namespace
- artifactory-ha.serviceAccount.name
#- postgresImage
- artifactory-ha.postgresql.postgresPassword
- artifactory-ha.artifactory.masterKey
- artifactory-ha.artifactory.node.replicaCount
- artifactoryImage
- artifactory-ha.artifactory.persistence.size
- artifactory-ha.artifactory.primary.resources.requests.cpu
- artifactory-ha.artifactory.primary.resources.requests.memory
- artifactory-ha.artifactory.primary.resources.limits.cpu
- artifactory-ha.artifactory.primary.resources.limits.memory
- artifactory-ha.artifactory.node.resources.requests.cpu
- artifactory-ha.artifactory.node.resources.requests.memory
- artifactory-ha.artifactory.node.resources.limits.cpu
- artifactory-ha.artifactory.node.resources.limits.memory
- artifactory-ha.artifactory.javaOpts.other
- artifactoryNginxImage
- artifactory-ha.nginx.service.type
