FROM docker.bintray.io/jfrog/artifactory-jcr:7.4.1

USER root
RUN mkdir -p /var/opt/jfrog/artifactory/etc/artifactory/info/
ADD info /var/opt/jfrog/artifactory/etc/artifactory/info/
RUN chown -R artifactory:artifactory /var/opt/jfrog/artifactory/etc/artifactory/

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE

USER artifactory