FROM docker.bintray.io/jfrog/nginx-artifactory-pro:$ARTIFACTORY_VERSION

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.nginx /docker/artifactory-pro/Dockerfile.GKE
