FROM releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:7.15.3

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.nginx /docker/artifactory-pro/Dockerfile.GKE
