FROM docker.bintray.io/jfrog/artifactory-jcr:$ARTIFACTORY_VERSION

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE