engine: gotpl
name: artifactory-mp
home: https://jfrog.com/container-registry/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-jcr/logo/jcr-logo.png
version: 3.2.0
appVersion: 7.10.2
description: JFrog Container Registry - The world’s most advanced, powerful, hybrid Docker and Helm registry.
keywords:
- artifactory
- jfrog
- container
- registry
- devops
sources:
- https://bintray.com/jfrog/product/JFrog-Container-Registry/view
- https://github.com/jfrog/charts
maintainers:
  - email: amithk@jfrog.com
    name: amithins
  - email: daniele@jfrog.com
    name: danielezer
  - email: eldada@jfrog.com
    name: eldada
  - email: rimasm@jfrog.com
    name: rimusz
  - email: vinaya@jfrog.com
    name: vinaya
apiVersion: v1
