#!/bin/bash

set -eo pipefail

# KUBE_CONFIG can point to a kubeconfig file or
# the standard kubectl config directory.
EXTRA_DOCKER_PARAMS=${EXTRA_DOCKER_PARAMS:-}
MARKETPLACE_TOOLS_TAG=${MARKETPLACE_TOOLS_TAG:-latest}
MARKETPLACE_TOOLS_IMAGE=${MARKETPLACE_TOOLS_IMAGE:-gcr.io/cloud-marketplace-tools/k8s/dev}

kube_mount="-v ${HOST_KUBE_CONFIG}:/mount/config/.kube/config:ro"
gcloud_mount="-v ${HOST_GCLOUD_CONFIG}:/mount/config/.config/gcloud:ro"

docker run \
  -v "/var/run/docker.sock:/var/run/docker.sock:ro" \
  --net=host \
  ${kube_mount[*]} \
  ${gcloud_mount[*]} \
  ${EXTRA_DOCKER_PARAMS[*]} \
  --rm \
  "${MARKETPLACE_TOOLS_IMAGE}:${MARKETPLACE_TOOLS_TAG}" \
  "$@"
